### ISSUE TITLE
Vlc for windows 7  with support  of yt-dlp

### ISSUE THREAD

**Issue by trimechee** [adeii/Qt6Win7#1]
Hi Mr @adeii , mercipour tous ces mangfiiques logiciels indipsensables life saver pour windows 7 os ! 💯 🥇 

i have request please: i don't know what happened, maybe google put pressure on vlc, but vlc no longer plays youtube videos, and vlc android has just announced that there will be a new version of vlc android after 6 months of interruption after having reached an agreement with google which suggests that the relationship between google and vlc is not at its best....

vlc 32 bits for windows 7 is one of the stable media players for windows 7 os, the problem vlc can no longer playback youtube videos and other sites like mail ru video..... I tried to find solutions:

because currently Vlc can't play youtube videos anymore......yes a vlc developer said that yt-dlp support is added to vlc 4, but the stable vlc 4 version is taking too long to come out because apparently there are still bugs to fix....

i found this software that allows to add yt-dlp support to the current 32-bit vlc version but it's a bit complicated, i tried and i couldn't get this software to work and play youtube videos .....:

A vlc addon for youtube-dl integration

https://github.com/mjasny/vlc-youtubeDL

https://www.remlab.net/vlc-plugin-ytdl/#:~:text=This%20stand%2Dalone%20open%2Dsource,VLC%20and%20LibVLC%2Dbased%20applications.

so we hope please that the generous Mr Adeii will solve this big problem and succeed to compile new version of vlc for windows 7  integrating yt-dlp to vlc player using vlc-youtubeDL or by other means, thank you!

also i found  the open source Gridplayer based on Vlc player has succeded to integrate yt-dlp to vlc :

https://github.com/vzhd1701/gridplayer

and

https://github.com/persimmonX/GridPlayer

some years ago when vlc could play youtube videos natively, some users complained that some youtube videos could not be played and this trick was posted to allow Vlc to play all these problematic videos :

VLC will not play videos with either ads or copyright-claimed material :

https://forum.videolan.org/viewtopic.php?p=483226#p483226

https://github.com/videolan/vlc/blob/master/share/lua/playlist/youtube.lua

Also i tried Vlc plugin of the famous 3D Youtube Source plugin 32 bits to add yt-dlp to Vlc player but sadly the plugin doens't work with Vlc :( 3D Youtube Source plugin 32 bits  works only for potlayer 32 bits  :

https://ys.3dyd.com/changelog/vlc/

Thanks !

**Comment by adeii** [comment]
Youtube-dl crashes on my PC, both inside and outside VLC. LUA script got backbone option to use yt-dlp if youtube-dl fails.
OK, yt-dlp with ffmpeg works fine - it streams YT video inside VLC (after downloading or buffering). 3DYD is added, also.
All are x86, should works on Win 7 32bit - maybe some dependencies needed.

https://github.com/adeii/Qt6Win7/releases/download/Test652/vlc-portable-3.0.21-x86.7z

**Comment by adeii** [comment]
That portable VLC is official build, but in *.zip. That yt-dlp is the same. You can delete youtube-dl.exe. And 3DYD is copy of official build, you can delete it too. This VLC should use yt-dlp and ffmpeg from plugins folder, unless you had installed these but in older version, in some of folder listed in user/system PATH.

**Comment by adeii** [comment]
no need anything to add, those are already in plugins/playlist, with vlc youtube lua script.

**Comment by adeii** [comment]
Aha. YT-DLP works fine on Win 8. Enable VxKex for it, to works on Win 7 until I found fix.

**Comment by adeii** [comment]
[youtube-dl.zip](https://github.com/user-attachments/files/17836273/youtube-dl.zip)
Replace youtube-dl.lua script in \lua\playlist with this one above.
It will try -f "best[height=480]" first, else -f "best[height=360]" for limit yt-dlp download/stream quality.

**Comment by adeii** [comment]
> we hope alos please youtube-dl.lua script will be compiled with the universal preset -f worstvideo or -f worst,

No need to compile. It is lua, not luac. Edit it however you like.

**Comment by Theo1996** [comment]
> So, I'll be honest, I would like to install Mr [@Blaukovitch](https://github.com/Blaukovitch)'s version of VxKex! but my biggest fear about VxKex is that the developer [@Theo1996](https://github.com/Theo1996) can no longer uninstall the old version of VxKex and can no longer install the new version of VxKex! :
> 
> [i486/VxKex#33](https://github.com/i486/VxKex/issues/33)
> 
> I fear if I install VxKex, I will no longer be able to uninstall this version of VxKex to install the possible future new version of VxKex and I prefer to wait for a new possible updated version of VxKex without bugs even if Mr [@adeii](https://github.com/adeii) told me that the development of VxKex may be put on hold for a long time.....
> 
> so Mr @[@Blaukovitch](https://github.com/Blaukovitch), can your version of VxKex be uninstalled without bug please?
> 
> https://github.com/Blaukovitch/VxKex

vxkex is okay now , i had a very old one, from the original repo that got banned
