### ISSUE TITLE
FFmpeg nonfree

### ISSUE THREAD

**Issue by trimechee** [adeii/Qt6Win7#3]
Hi, so to avoid tiring you and asking for a new version of the amazing vlc portable remastered just because a new version of yt-dlp or ffmpeg has been released, because ffmpeg no longer offers versions for windows 7 os, and in addition I know open source downloders yt-dlp GUI who refuse to install ffmpeg and yt-dlp and ask the user to manually install ffmpeg and yt-dlp himself, I would like to know where to find the trusted and updated version of ffmpeg 32 bits for windows 7 os 32 bits used by vlc portable please?

I did some research, is this ffmpeg complied by sudo-nautilus please?

https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/releases/tag/latest

in this case please, which version to choose between ffmpeg gpl, lgpl..... ?

i also found a "nonfree" ffmpeg that seems to overcome some of the limitations of the official ffmpeg, what do you think please? it's a good idea to use this fork of ffmpeg that could perhaps fix some problems, for example it will allow vlc portable to playback videos from mail ru videos?

Automated nonfree builds of FFmpeg for Windows using GitHub Actions:

https://github.com/AnimMouse/ffmpeg-autobuild
https://www.animmouse.com/projects/ffmpeg-autobuild/

other builds of FFmpeg built by others
https://www.animmouse.com/p/ffmpeg-binaries/

**Comment by adeii** [comment]
I dunno. I guess, ffmpeg gpl.

**Comment by adeii** [comment]
Yes, that is the one. But it is 1,5 years old.
https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/releases/download/latest/ffmpeg-master-latest-win32-gpl.zip

It you find some newer, x86, working on Win7 (even with VxKex only), overwrite previous one.
