### ISSUE TITLE
New problem : VLC portable doesn't playback youtube videos anymore  

### ISSUE THREAD

**Issue by trimechee** [adeii/Qt6Win7#4]
Hi, this is just for information and there is no need to fix this problem since there is potplayer, it seems that vlc portable can no longer playback youtube video, maybe youtube can detect the user agent of vlc and block it....we hope vlc 4 will be released soon and add native support for yt-dlp...

**Comment by adeii** [comment]
Not problem with VLC, just use latest yt-dlp. Additional program could be https://github.com/ErrorFlynn/ytdlp-interface/releases/tag/v2.14.1 .
