### ISSUE TITLE
Make easy executable version of the last new version vital life saver build-win-nt6_0-x86 of N_m3u8DL-RE to be able to donwload crypted hls videos in our windows 7 os 32 bits please ! 

### ISSUE THREAD

**Issue by trimechee** [adeii/Qt6Win7#5]
Hello, we now that Mr Adeii has already offers us compiled special version of N_m3u8DL-RE for windows 7 os 32 bits, thanks ! but new versions has bee published to fix serious bugs and here i explai why this software is vital for windows 7 users :  so me, and certainly many others, have weak laptops old windows 7 os 32 bits, streaming videos may lag buffer jerks, even preview with potplayer with cat catch extension lag sometimes because my internet connection can become very weak....

the solution is to download, some hls video require to merge audio and video and cat catch extension to a site: ffmpeg online for merge audio and video but my old cpu does not support some ffmpeg online instructions, cat catch recommends to use an external parser m3u8 mpd parser: the great N_m3u8DL-RE, N_m3u8DL-RE is compatible only with windows 10 and 11 but great Mr Adeii and also the developer of N_m3u8DL-RE the great Mr Nilaoda accepts following my request to make N_m3u8DL-RE compatible with my windows 7 os 32 bits! the little problem N_m3u8DL-RE is updated regularary but still in beta phase and I would like to use the last new version right now to be able to download videos and avoid network buffer lag but I can't find the beta executable version for my windows 7 os 32 bits, I'm not an expert so I don't know what to do and we hope the great Mr @adeii  will compile the last new beta .exe version of N_m3u8DL-RE for windows 7 os 32 bits please, thank you!

build-win-nt6_0-x86 :

https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/12132261757/job/33825846172

**Comment by adeii** [comment]
Well, you are looking for arfact from that action.
https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/12132261757/artifacts/2265142941
NT6.0 means you need .net 6.0 installed.

**Comment by adeii** [comment]
New version need .NET 9 for compiling.
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-9.0.101-windows-x86-binaries

https://github.com/adeii/Qt6Win7/releases/download/Tests/N_m3u8DL-RE-dec24.7z v.0.3.0.0
