### ISSUE TITLE
New version of Mpc-qt

### ISSUE THREAD

**Issue by trimechee** [adeii/Qt6Win7#6]
Hi, i see Mpc-qt made new version, what do you think Mr @adeii ? the new upgrade version can be compatible with windows 7? we obviously hope, if it doesn't bother you and if it is technically possible, a Mpc-qt version for windows 7 os 32 bits please, because even if potplayer works,  we don't know if potplayer will continue to support windows 7 os....

i'm even ready to install VxKex even if this program seems to no longer be updated !

**Comment by adeii** [comment]
For now, try this https://github.com/zaps166/QMPlay2/releases/download/24.12.06/QMPlay2-Win32-24.12.06-qt5.exe

**Comment by trimechee** [comment]
Great ! Thanks :) 💯

**Comment by trimechee** [comment]
Mr Adeii @adeii , hi again, i test Mpc qt that you kindly sent to me, , i have errror message :"your computer lacks api ms win core path  1 1 0.dll , try ristall the program to fix the problem", 

so i suppose we should install vkkex ?

**Comment by adeii** [comment]
https://www.dll-files.com/download/0ed28b807adb89aa37f9b3c057134f4a/api-ms-win-core-path-l1-1-0.dll.html?c=S3ZtanpHV3pNVkE4WFFqQnNPeGorUT09

[api-ms-win-core-path-l1-1-0.zip](https://github.com/user-attachments/files/18220035/api-ms-win-core-path-l1-1-0.zip)

**Comment by trimechee** [comment]
Great ! Thank you so much :)

**Comment by trimechee** [comment]
Hi Mr @adeii , i see there is new update of the real Vxkex in october, the releases notes changelog say : 

"- Fixed a propagation bug which caused VxKex to not be able to run on
      32-bit operating systems."


so do think the new stable new version of Vxkex is sufficient for mpc qt or we still have to install these software syou kindly sent me?


 https://www.dll-files.com/download/0ed28b807adb89aa37f9b3c057134f4a/api-ms-win-core-path-l1-1-0.dll.html?c=S3ZtanpHV3pNVkE4WFFqQnNPeGorUT09

[api-ms-win-core-path-l1-1-0.zip](https://github.com/user-attachments/files/18220035/api-ms-win-core-path-l1-1-0.zip)
