### ISSUE TITLE
The ultimate dream: Compile a version of Brisk download manager which adds support for download streaming video and sequentia donwload for windows 7 os 32 bits please!

### ISSUE THREAD

**Issue by trimechee** [adeii/Qt6Win7#7]
Hi, the great Mr Adeii is known for his great generosity and he has already generously compiled several modern software for our windows 7 os 32 bits, thank you very much!

so Brisk download manager becomes the best download manager in the world because the great Mr Amin listened to my suggestions and added streaming video download support and sequential download to playback the video while downloading!

https://github.com/AminBhst/brisk

the only problem Brisk is not compatible with my windows 7 OS 32 bits,

I talked about this ultimate dream in Mr Amin's github:

https://github.com/AminBhst/brisk/issues/69

the dream is that Mr Adeii offers us a version of Brisk for windows 7 os please!

I don't know if Mr Adeii will accept this challenge and if it is technically possible to compile version of Brisk for windows 7 os 32 bits, but I am sure that great Mr Amin will be able to help Mr Adeii if Mr Adeii accepts this challenge and if it is technically possible, we know this is of course very complex, so we hope please for a fruitful technical discussion between Mr Mr @adeii and Mr @AminBhst if this dream can become true and maybe Mr Amine can make some modifications to the source code to help Mr Adeii to possibly support legacy windows 7 32-bit os, thanks!

**Comment by adeii** [comment]
No way. There is no Flutter x86 and even x64 version wont work on Win 7 with VxKex.
Older DART SDK wont compile x86 executable after all.
Use some usual alternative like 
https://jdownloader.org/dl?v=101
https://www.downthemall.org
https://github.com/subhra74/xdm/releases/download/8.0.29/xdmsetup-8.0.29-win7.msi
https://github.com/aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0-win-32bit-build1.zip
https://dl.motrix.app/release/Motrix-1.8.19-ia32-win.zip

**Comment by adeii** [comment]
https://chromewebstore.google.com/detail/the-stream-detector/iakkmkmhhckcmoiibcfjnooibphlobak

https://www.hlsloader.com/sr/record.html?s=a548ba60

**Comment by trimechee** [comment]
UPDATE : 
Hi Mr Adeii, i have great news, no more nedd to download manager to playback video while donwloading ! 


Mr Chandler the developer of Live stream downloader tells me today he does not encounter this problem and he can playback the temporary video while it is downloading ..... this prompted me to install updated chrome browser for windows 7 made by Mr Blaukovitch :

https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7

and the dream comes true !! I can see and playback the video while it is downloading which is vital for me who has a weak connection weak cpu !

https://v6.voiranime.com/anime/ao-no-exorcist-4-yuki-no-hate-hen-vf/ao-no-exorcist-4-01-vf/

Huge thanks thanks and gratitude to Mr @adeii for informing me about this great vital web browser chrome for windows 7 !! 💯 🥇 

success with GOOGLE_CHROME_Windows_7 pushes me to try Mozilla_Firefox_Windows_7 :

https://github.com/Blaukovitch/Mozilla_Firefox_Windows_7

to see if the browser can display the temporary video but my dream does not come true, apparently Mozilla_Firefox_Windows_7 is only compatible with windows 7 64bits, Mr Adeii, of course I'm not asking you to do such complex thing  since there is Firefox esr for Windows 7, but but it's just to know , why Mozilla_Firefox_Windows_7 doesn't have 32-bits version ?

**Comment by trimechee** [comment]
UPDATE :

my success with chrome for windows 7 prompted me to reinstall yandex browser compatible with my windows 7 os 32 bots and I can see and playback the temporary video while it is downloading using Live stream downloader alhammdoulilAllah, thank's God !!!

https://browser.yandex.com/

yandex uses chromium 128 kernel, I advise to disable unnecessary options such as launching at computer startup, staying in the background.....


Mr @adeii , I thank you immensely for your generosity in helping me compile a special version N_m3u8DL-RE for my windows7 os 32 bits! 💯 🥇 and sorry for tiring you!

even though Cat-Catch developer recommends to use N_m3u8DL-RE to skip some webassembly video size limit of 1.8GB in chrome(this limit does not exist in firefox) and to merge audio and video of certai complex videos..... and since cat catch and live stream downloader extensions can display temporary video while downloading and we can playback temporary  video when we use chrome and yandex for windows 7 os, I think, as long as these extensions can download videos without needing external parser, I think for now i think we don't need  the great N_m3u8DL-RE , I say this to not tire you  to compiling N_m3u8DL-RE every time there is new version :) 

if streams become more complex and we need an external parser like awesome  N_m3u8DL-RE to download them, I will contact you and you judge if you like or not  compile N_m3u8DL-RE for windows 7 os.... thanks!

**Comment by trimechee** [comment]
update : 
Mr @adeii , Great news, alhamdoulilAllah i find the solution to display temporary video in chromium browsers and fix this major problem !! so for now, no more need to compile N_m3u8DL-RE  :) 

https://github.com/win32ss/supermium/issues/1064

**Comment by trimechee** [comment]
also i discover disable "continue running applications in the background after closing chrome" causes problem with preview feature of Open-in vlc and Cat catch, enable continue running applications in the background after closing chrome" allows to solve the problem of preview with potplayer!
